import React, {useState, useEffect }from 'react';

import {Loader, Card, FormField} from '../components';

const RenderCards = ({data, title}) => {
    // shows all posts if there are any
    if (data?.length > 0) {
        return data.map((post) => <Card key={post._id} {...post} />)
    } 
    return(
        <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
    )
}

function Home() {
    const [loading, setloading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText, setsearchText] = useState('');
    const [searchResults, setSearchResults] = useState(null);
    const [searchTimeout, setSearchTimeout] = useState(null);

    useEffect(() => {
        const fetchPosts = async () => {
            setLoading(true);
            try {
                const response = await fetch('http://localhost:8080/api/v1/post', {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json',
                    }
                });
                if (response.ok) {
                    const data = await response.json();
                    setAllPosts(data.data);
                }
            } catch (error) {
                console.error(error);
            }
            setLoading(false);
        };
        fetchPosts();
    }, []);

    const handleSearchChange = (e) => {
        clearTimeout(searchTimeout);
        setsearchText(e.target.value);

        setSearchTimeout(
            setTimeout(() => {
                const searchResults = allPosts.filter((post) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
                setSearchResults(searchResults);
            },500)
        );   
        }


    return (
        <section className="max-w-7x1 mx-auto">
            <div>
                <h1 className="font-extrabold text-[#222328] text-[16px]">The Community Showcase</h1>
                <p className="mt-2 text-[#666e75] text-[14px] max-w[500px]">Browse through a collection of imaginative and visually stunning images generated by Virtuoso AI.</p>
            </div>

            <div className="mt-16">
                <FormField 
                    labelName="Search Post"
                    type="text"
                    name = "text"
                    placeholder="Search by name or prompt"
                    value = {searchText}
                    handleChange={handleSearchChange}                
                />
            </div>

            <div className="mt-10">
                {loading? (
                    <div className="flex justify-center items-center">
                        <Loader />
                    </div>
                ): (
                    <>
                        {searchText && (
                            <h2 className='font-medium text-[#666e75] text-xl mb-3'>Showing results for <span className='text-[#222328]'>{searchText} </span></h2>
                        )}
                    </>
                )}
            </div>

            <div >
                {searchText ? (
                    <RenderCards 
                        data={[searchResults]}
                        title="No search results found"
                    />
                    ) : (
                        <RenderCards 
                            data={allPosts}
                            title="No posts to show"
                        />
                    )}
            <image src="C:\Users\Dwija\Pictures\Screenshots\Screenshot 2024-03-19 153017.png"></image>
            </div>
        </section>
  )
}

export default Home